SET DEFINE OFF;
Insert into FLEX.SA_ROLE
   (ROLE_ID, NAME, DESCRIPTION, ROLE_TYPE_ID, USER_OWNER_ID)
 Values
   (-99, 'DEVELOPER', 'Rol para desarrolladores', 2, 1);
Insert into FLEX.SA_ROLE
   (ROLE_ID, NAME, DESCRIPTION, ROLE_TYPE_ID, USER_OWNER_ID)
 Values
   (2, 'CONN_ROLE_OPENFLEXIS', 'Rol de conexion', 2, 1);
Insert into FLEX.SA_ROLE
   (ROLE_ID, NAME, DESCRIPTION, ROLE_TYPE_ID, USER_OWNER_ID)
 Values
   (172, 'RL TECNO AUX PRESENC <=5 SMLMV', 'RL TECNO AUX PRESENC <=5 SMLMV', 2, 1);
Insert into FLEX.SA_ROLE
   (ROLE_ID, NAME, DESCRIPTION, ROLE_TYPE_ID, USER_OWNER_ID)
 Values
   (173, 'RL TECNOLO GCIA ATC <=10 SMLMV', 'RL TECNOLO GCIA ATC <=10 SMLMV', 2, 1);
Insert into FLEX.SA_ROLE
   (ROLE_ID, NAME, DESCRIPTION, ROLE_TYPE_ID, USER_OWNER_ID)
 Values
   (189, 'EJECUTABLES_CUSTOMIZAC_EPM', 'EJECUTABLES_CUSTOMIZAC_EPM', 2, 9975);
COMMIT;
