SET DEFINE OFF;
Insert into FLEX.SA_ROLE_EXECUTABLES
   (ROLE_ID, EXECUTABLE_ID)
 Values
   (172, 347);
Insert into FLEX.SA_ROLE_EXECUTABLES
   (ROLE_ID, EXECUTABLE_ID)
 Values
   (172, 136932);
COMMIT;
