SET DEFINE OFF;
Insert into FLEX.SA_ROLE_EXECUTABLES
   (ROLE_ID, EXECUTABLE_ID)
 Values
   (173, 347);
Insert into FLEX.SA_ROLE_EXECUTABLES
   (ROLE_ID, EXECUTABLE_ID)
 Values
   (173, 136932);
COMMIT;
