//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarQ.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarQ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a objetos.
        /// </summary>
        internal static string CarpetaObjetos {
            get {
                return ResourceManager.GetString("CarpetaObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sonar.
        /// </summary>
        internal static string CarpetaSonar {
            get {
                return ResourceManager.GetString("CarpetaSonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sonar-scanner.properties.
        /// </summary>
        internal static string NombreSonarConn {
            get {
                return ResourceManager.GetString("NombreSonarConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sonar-project.properties.
        /// </summary>
        internal static string NombreSonarProperties {
            get {
                return ResourceManager.GetString("NombreSonarProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #Configure here general information about the environment, such as SonarQube server connection details for example
        ///#No information about specific project should appear here
        ///
        ///#----- Default SonarQube server
        ///#sonar.host.url=http://localhost:9000
        ///#----- Default source code encoding
        ///#https://sonar.epm.com.co/sonar/projects
        ///#sonar.sourceEncoding=UTF-8
        ///sonar.host.url= https://sonar.epm.com.co/sonar
        ///sonar.login=[usuario]
        ///sonar.password=[pass].
        /// </summary>
        internal static string SonarConn {
            get {
                return ResourceManager.GetString("SonarConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #sonar-project.properties
        ///# must be unique in a given SonarQube instance
        ///sonar.projectKey=Open
        ///
        ///# --- optional properties ---
        ///
        ///# defaults to project key
        ///sonar.projectName=Open
        ///# defaults to &apos;not provided&apos;
        ///#sonar.projectVersion=1.0
        /// 
        ///# Path is relative to the sonar-project.properties file. Defaults to .
        ///sonar.sources=[ruta]
        ///sonar.language=plsql
        ///#sonar.branch=desarrollo
        ///sonar.branch.name=[rama]
        ///# Encoding of the source code. Default is default system encoding
        ///#sonar.sourceEncoding=UTF-8
        ///sona [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SonarProperties {
            get {
                return ResourceManager.GetString("SonarProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] SonarZip {
            get {
                object obj = ResourceManager.GetObject("SonarZip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sonarq.zip.
        /// </summary>
        internal static string ZipZonar {
            get {
                return ResourceManager.GetString("ZipZonar", resourceCulture);
            }
        }
    }
}
